pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:15-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('DATABASE') {
      agent {
        docker { image 'mysql:8.0' }
      }
      steps {
        sh 'mysql --version'
      }
    }
  }
}
